# Generated by Django 6.0.7 on 2026-07-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_alter_invitation_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CUSTOMER_CREATED', 'Customer Created'), ('CUSTOMER_UPDATED', 'Customer Updated'), ('CUSTOMER_DELETED', 'Customer Deleted'), ('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_DELETED', 'Task Deleted'), ('ORGANIZATION_CREATED', 'Organization Created'), ('MEMBER_INVITED', 'Member Invited')], max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='organizations.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
