# Generated by Django 6.0.7 on 2026-07-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_invitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set(),
        ),
    ]
