# Generated by Django 6.0.7 on 2026-07-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_invitation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
